#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'fileutils'
require 'open3'
require 'time'

module Sbom
  # Configuration constants
  DEFAULT_CVE_DB_PATH = File.expand_path('../cve_db.json', __FILE__) rescue '/etc/cve_db.json'
  DEFAULT_EOL_KERNELS = {
    '2.6.32' => Time.parse('2015-01-01'),
    '3.2.0'  => Time.parse('2014-06-01'),
    '3.4.11' => Time.parse('2013-09-01'),
    '3.8.13' => Time.parse('2015-03-01'),
    '4.1.15' => Time.parse('2016-06-01'),
    '4.4.17' => Time.parse('2017-09-01'),
    '4.9.8'  => Time.parse('2018-12-01'),
    '5.4.39' => Time.parse('2019-06-01'),
    '5.10.7' => Time.parse('2020-09-01')
  }

  # Common ELF paths to check for binaries
  BINARY_PATTERNS = [
    /bin\/(sh|bash|zsh|ash|csh|ksh)$/,
    /lib(?:64)?\/(ld-linux|x86_64-linux-gnu)/,
    /usr\/lib(?:64)?\/(libc.so|libpthread.so)/,
    /boot\/vmlinuz-?([0-9.]+)(?:-[a-z0-9_-]*)?$/,
    /etc\/(bashrc|profile|motd)$/,
    /etc\/ssl\/certs\/ca-certificates.crt$/
  ]

  # Common config patterns for package detection
  CONFIG_PATTERNS = [
    /etc\/apt\/sources.list/,
    /etc\/yum\/repos\.d/,
    /var\/lib\/dpkg\/status/,
    /var/lib/rpm/Package-*.rpm/,
    /usr/share/doc/\w+\/copyright$/i,
    /usr/share/doc/\w+/changelog$/i
  ]

  # Known CVEs for common components (sample - extend as needed)
  KNOWN_CVES = {
    'glibc' => [
      { version: '<2.31', cve_id: 'CVE-2021-43896', severity: 'HIGH', description: 'Heap buffer overflow in glibc' },
      { version: '<2.35', cve_id: 'CVE-2021-43897', severity: 'MEDIUM', description: 'Integer underflow in glibc' }
    ],
    'openssl' => [
      { version: '<1.1.1k', cve_id: 'CVE-2021-3711', severity: 'HIGH', description: 'TLS renegotiation DoS' },
      { version: '<1.1.1l', cve_id: 'CVE-2021-4489', severity: 'CRITICAL', description: 'Heartbleed variant' }
    ],
    'bash' => [
      { version: '<5.0', cve_id: 'CVE-2019-20267', severity: 'HIGH', description: 'Stack-based buffer overflow' },
      { version: '<4.3.48', cve_id: 'CVE-2019-20275', severity: 'MEDIUM', description: 'Arbitrary code execution via symlink' }
    ]
  }

  # CycloneDX schema version
  SCHEMA_VERSION = '1.6'

  class << self
    def create_sbom(root_path, output_file = nil)
      root_path = File.expand_path(root_path) unless File.absolute_path?(root_path)
      output_file ||= "#{root_path}/sbom.json"

      puts "Scanning filesystem: #{root_path}"
      sbom = CycloneDXBuilder.new(SCHEMA_VERSION)

      # Traverse and identify components
      component_map = {}
      traverse_directory(root_path, root_path, component_map)

      # Build final SBOM from collected data
      sbom.add_components(component_map.values)

      # Check for CVEs
      flagged = check_cves(sbom.components)

      # Check for EOL kernels
      eol_kernels = check_eol_kernels(root_path)

      # Add notes about findings
      if flagged.any? || eol_kernels.any?
        sbom.add_notes(
          "SBOM generated by Sbom::CycloneDXBuilder",
          "CVE Flags: #{flagged.size}",
          "EOL Kernels: #{eol_kernels.size}"
        )
      end

      # Output result
      output = JSON.pretty_generate(sbom.to_cyclonedx)
      File.write(output_file, output)

      puts "SBOM written to: #{output_file}"
      puts "Components found: #{sbom.components.size}"
      puts "CVE flags: #{flagged.size}, EOL kernels: #{eol_kernels.size}"

      [sbom.to_cyclonedx, flagged, eol_kernels]
    end

    private

    def traverse_directory(dir, relative_path, components)
      return if File.directory?(dir) && (File.symlink?(dir) || dir == '.')

      # Check for binaries and libraries
      BINARY_PATTERNS.each do |pattern|
        matches = Dir.glob(File.join(dir, pattern))
        matches.each do |match|
          rel_path = relative_path.sub(/^#{Regexp.escape(relative_path)}\//, '')
          components[rel_path] ||= Component.new(match, relative_path)
        end
      end

      # Check for config files that indicate packages
      CONFIG_PATTERNS.each do |pattern|
        matches = Dir.glob(File.join(dir, pattern))
        matches.each do |match|
          rel_path = relative_path.sub(/^#{Regexp.escape(relative_path)}\//, '')
          components[rel_path] ||= ConfigComponent.new(match, relative_path)
        end
      end

      # Recurse into subdirectories (limit depth for performance)
      Dir.entries(dir).select { |e| e != '.' && e != '..' }.sort.each do |entry|
        next if File.directory?(File.join(dir, entry)) && (File.symlink?(File.join(dir, entry)) || relative_path == '.')

        new_rel = "#{relative_path}/#{entry}"
        traverse_directory(File.join(dir, entry), new_rel, components)
      end
    end

    def extract_version_from_binary(path)
      return nil unless File.file?(path)

      # Try to read ELF header
      begin
        data = File.read(path, 52)
        if data[0] == "\x7f" && data[1..3] == "ELF"
          # Basic ELF detection - try to get version from strings
          output = Open3.capture_output("strings #{path} 2>/dev/null | grep -oP '(?<=(version|VER|VERSION))\s*\K[\d.]+')
          return output.first if output.any?
        end
      rescue
        # Binary might be compressed or in unusual format
      end

      nil
    end

    def extract_version_from_config(path)
      return nil unless File.file?(path)

      content = File.read(path, 4096)
      patterns = {
        /version\s*=\s*["']?(\d+\.\d+(?:\.\d+)?)["']?/i => :direct,
        /VERSION\s*=\s*["']?(\d+\.\d+(?:\.\d+)?)["']?/i => :direct,
        /Release:\s*(\d+\.\d+(?:\.\d+)?)/i => :direct
      }

      patterns.each do |pattern, type|
        match = content.match(pattern)
        return match[1] if match && (type == :direct || !match[1].nil?)
      end

      nil
    end

    def check_cves(components)
      flagged = []

      components.each do |comp|
        next unless comp.respond_to?(:version) && comp.version

        KNOWN_CVES.each do |(name, cve_list)|
          if name.downcase.include?(comp.name.to_s.downcase) ||
             name.downcase.include?(/glibc|bash|openssl/i) && (comp.path.include?('lib') || comp.path.include?('/bin/'))
            cve_list.each do |cve|
              ver = Gem::Version.new(comp.version)
              if cve[:version]
                threshold = Gem::Version.new(cve[:version].gsub('<', '').strip)
                if ver < threshold
                  flagged << { component: comp, cve: cve }
                end
              elsif cve[:cve_id] == 'CVE-2019-20267' || cve[:cve_id] == 'CVE-2019-20275' # Bash specific
                  if comp.name.include?('bash')
                    flagged << { component: comp, cve: cve }
                  end
                end
            end
          end
        end
      end

      flagged
    end

    def check_eol_kernels(root_path)
      eol = []

      # Check boot directory for kernels
      kernel_dir = File.join(root_path, 'boot')
      if File.directory?(kernel_dir)
        Dir.glob(File.join(kernel_dir, 'vmlinuz-*')).each do |kern|
          rel_path = kern.sub(/^#{Regexp.escape(kernel_dir)}\//, '')

          # Extract version from filename
          match = rel_path.match(/vmlinuz-?(\d+\.\d+(?:\.\d+)?)/)
          if match
            ver_str = match[1]
            eol_date = DEFAULT_EOL_KERNELS[ver_str] || nil

            if eol_date && Time.now > eol_date
              eol << { path: rel_path, version: ver_str, eol_date: eol_date }
            end
          end
        end
      end

      # Check /proc/version for running kernel (if available)
      begin
        proc_version = Open3.capture_output('cat /proc/version 2>/dev/null').first
        if proc_version.include?('Linux version')
          match = proc_version.match(/Linux version\s+(\d+\.\d+(?:\.\d+)?)/i)
          if match
            ver_str = match[1]
            eol_date = DEFAULT_EOL_KERNELS[ver_str] || nil

            if eol_date && Time.now > eol_date
              eol << { path: '/proc/version', version: ver_str, eol_date: eol_date }
            end
          end
        end
      rescue
        # /proc not available or error reading
      end

      eol
    end
  end
end

# ============================================================================
# CycloneDX Builder - Generates valid CycloneDX JSON output
# ============================================================================

class CycloneDXBuilder
  def initialize(version = '1.6')
    @version = version
    @components = []
    @bom_ref = 'sbom-0'
    @metadata = {
      timestamp: Time.now.iso8601,
      tools: [{ name: 'Sbomb', version: '1.0.0' }]
    }
  end

  def add_component(component)
    # Extract component data from our internal format
    comp_data = extract_component_data(component)
    @components << comp_data if comp_data
    self
  end

  def add_components(components_array)
    components_array.each { |c| add_component(c) }
    self
  end

  def add_notes(*notes)
    return unless notes.any?
    @metadata[:component] = [{ name: 'Sbomb', version: '1.0.0' }] if !@metadata.key?(:component)
    @metadata[:notes] ||= []
    notes.each do |note|
      @metadata[:notes] << { text: note, time: Time.now.iso8601 }
    end
    self
  end

  def to_cyclonedx
    # Build the final CycloneDX structure
    components_json = @components.map { |c| c.to_h }.join(',')

    result = {
      '$schema' => "http://cyclonedx.org/schema/bom-#{@version}.json",
      'bomFormat' => 'CycloneDX',
      'specVersion' => { name: 'CycloneDX', version: @version },
      'metadata' => @metadata,
      'components' => components_json.empty? ? [] : [components_json]
    }

    # Add vulnerabilities if any were flagged
    result['vulnerabilities'] = @metadata[:notes].map do |note|
      {
        'id' => note[:text],
        'severity' => note[:severity] || 'UNKNOWN',
        'description' => note[:text],
        'cveIds' => [note[:text]] if note.key?(:text) && note[:text].include?('CVE-')
      }
    end.compact

    result.delete('vulnerabilities') unless result['vulnerabilities'].any?

    result
  end

  private

  def extract_component_data(component)
    return nil unless component.respond_to?(:name) || component.respond_to?(:path)

    name = component.name.to_s.strip || File.basename(component.path, '.*').strip
    version = component.version || 'unknown'
    type = determine_type(name, component.path)

    {
      'type' => type,
      'name' => name,
      'version' => version,
      'bom-ref' => "#{@bom_ref}-#{SecureRandom.uuid[0..8]}",
      'purl' => build_purl(name, version, type)
    }
  end

  def determine_type(name, path)
    if name.include?('.so') || name.include?('.a') || name.include?('.lib')
      'library'
    elsif name.include?('.sh') || name.include?('/bin/') && (name.include?('bash') || name.include?('sh'))
      'application'
    elsif name.include?('kernel') || name.include?('vmlinuz')
      'firmware'
    else
      'application'
    end
  end

  def build_purl(name, version, type)
    base = "#{type}:"
    if name.include?('/')
      # Handle names with slashes (e.g., /usr/lib/libc.so.6)
      parts = name.split('/').last.split('.')
      name_part = parts.first || 'unknown'
      purl = "#{base}#{name_part}@#{version}"
    else
      purl = "#{base}#{name}@#{version}"
    end

    # Add namespace if it looks like a package manager path
    if name.include?('/usr/')
      ns = File.dirname(name).split('/').first(2).join('/')
      purl = "pkg:gem/#{ns}/#{name_part}@#{version}"
    end

    purl
  end
end

# ============================================================================
# Component classes for different file types
# ============================================================================

class Component
  attr_reader :path, :name, :version

  def initialize(path, relative_path = nil)
    @path = path
    @relative_path = relative_path || File.basename(path).to_s
    @extracted_version = extract_version_from_binary(path)
  end

  def name
    @name ||= File.basename(@path, '.*').strip
  end

  def version
    @version ||= @extracted_version
  end

  def to_h
    { path: @path, name: @name, version: @version }
  end
end

class ConfigComponent < Component
  attr_reader :config_path

  def initialize(config_path, relative_path = nil)
    super(config_path, relative_path)
    @extracted_version = extract_version_from_config(config_path)
  end

  def name
    @name ||= File.basename(@config_path, '.*').strip
  end

  def to_h
    { config: true, path: @path, name: @name, version: @version }
  end
end

# ============================================================================
# Main entry point and demo
# ============================================================================

if __FILE__ == $0
  # Default behavior: scan current directory if no args provided
  root = ARGV.first || '.'

  begin
    result = Sbom.create_sbom(root)
    cyclonedx, flagged, eol = result

    puts "\n=== SBOM Summary ==="
    puts "Total components: #{cyclonedx['components'].size}"
    puts "Flagged CVEs: #{flagged.size}"
    puts "EOL Kernels: #{eol.size}"

    if flagged.any?
      puts "\n=== Flagged CVEs ==="
      flagged.each do |